name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: swift-foundations/.github/.github/workflows/swift-ci.yml@main
    with:
      integrated-docs: true
      docs-umbrella-module: HTML_Rendering
      docs-umbrella-display-name: HTML Rendering
      docs-umbrella-bundle-id: swift-html-render.HTML-Rendering
      docs-umbrella-docc-path: Sources/HTML Rendering/HTML Rendering.docc
      docs-exclude-modules: HTML_Rendering_Core_Test_Support
    secrets: inherit
